-- Packmate: initial sync schema.
--
-- Mirrors the on-device SQLite schema (local schema v4) so the app's local-first
-- sync engine has somewhere to push to and pull from. Nothing here is the source
-- of truth: the phone is. This is a mirror that also happens to make the data
-- reachable from a server, which is what the later AI itinerary planner needs.
--
-- Apply with either:
--   supabase db push
--   -- or paste into the SQL editor in the Supabase dashboard
--
-- After applying, in Authentication → Providers, enable **anonymous sign-ins**
-- (and turn on captcha / rate limiting for that endpoint), because the app
-- signs in anonymously the moment a user opts into backup.


-- ============================================================================
-- Conventions, and the contract with the client
-- ============================================================================
--
-- * `uuid` is the primary key and is generated by the client. Local integer ids
--   never leave the device — the same trip is id 3 on a phone and 17 on a
--   tablet, and neither cares.
--
-- * `user_id` defaults to auth.uid(), so the client never sends it. That is what
--   makes "claim my existing data on first sync" free: rows just land owned.
--
-- * Timestamps are `bigint` epoch **milliseconds**, matching the Dart models'
--   storage format exactly. Converting on the wire would invite a silent
--   timezone bug (`DateTime.fromMillisecondsSinceEpoch` is local, and
--   `toIso8601String()` on a local DateTime emits no offset) — and that bug
--   would corrupt checkout reminder times. Each one gets a generated
--   `timestamptz` twin so humans, dashboards, and the later AI phase can still
--   write ordinary date SQL.
--
-- * `updated_at` is always assigned by the server, never by the client. Device
--   clocks are wrong, sometimes by hours, and the client uses `updated_at` as a
--   sync cursor — one bad clock could otherwise poison the cursor space and
--   suppress pulls on every device. The trigger below enforces this: a client
--   *cannot* set it, even deliberately.
--
-- * Deletes are soft here (`deleted_at`), because another device has to be able
--   to learn about them. Locally the app hard-deletes and records a tombstone
--   separately, so no local query needs a "not deleted" filter.
--
-- Column name mapping — the client speaks camelCase (its model field names),
-- these tables are snake_case, and the Supabase adapter translates. Keep this
-- table and the adapter in step:
--
--   trips               uuid, name, startDate→start_date, endDate→end_date
--   stays               uuid, tripUuid→trip_uuid, hotelName→hotel_name,
--                       checkInAt→check_in_at, checkOutAt→check_out_at
--   transport_legs      uuid, tripUuid→trip_uuid, type,
--                       departureAt→departure_at, fromLocation→from_location,
--                       toLocation→to_location
--   items               uuid, tripUuid→trip_uuid, name, category, quantity,
--                       packed  (int 0/1 locally → boolean here)
--   packing_lists       uuid, name, createdAt→created_at
--   packing_list_items  uuid, listUuid→list_uuid, name, category, quantity
--
-- `documents` is created but deliberately NOT synced yet: its local `photoPath`
-- is a device file path, meaningless on another phone and stale even on the same
-- one after a reinstall. It gets a `storage_key` instead, for when the Documents
-- feature is actually built on top of Supabase Storage.


-- ============================================================================
-- Server-assigned timestamps
-- ============================================================================

create or replace function public.set_row_updated()
returns trigger
language plpgsql
as $$
begin
  -- Overwrites whatever the client sent. This is deliberate: the cursor space
  -- belongs to the server clock alone.
  new.updated_at := (extract(epoch from now()) * 1000)::bigint;
  return new;
end;
$$;

comment on function public.set_row_updated() is
  'Forces updated_at to server time on every write, so a client with a wrong '
  'clock cannot corrupt the sync cursor space.';


-- ============================================================================
-- Tables
-- ============================================================================

create table public.trips (
  uuid        uuid primary key,
  user_id     uuid not null default auth.uid()
                references auth.users (id) on delete cascade,
  name        text not null,
  start_date  bigint not null,
  end_date    bigint not null,
  updated_at  bigint not null default 0,
  deleted_at  bigint,
  start_at    timestamptz generated always as
                (to_timestamp(start_date / 1000.0)) stored,
  end_at      timestamptz generated always as
                (to_timestamp(end_date / 1000.0)) stored,
  updated_at_ts timestamptz generated always as
                (to_timestamp(updated_at / 1000.0)) stored
);

create table public.stays (
  uuid          uuid primary key,
  user_id       uuid not null default auth.uid()
                  references auth.users (id) on delete cascade,
  trip_uuid     uuid not null references public.trips (uuid) on delete cascade,
  hotel_name    text not null,
  check_in_at   bigint not null,
  check_out_at  bigint not null,
  updated_at    bigint not null default 0,
  deleted_at    bigint,
  check_in_ts   timestamptz generated always as
                  (to_timestamp(check_in_at / 1000.0)) stored,
  check_out_ts  timestamptz generated always as
                  (to_timestamp(check_out_at / 1000.0)) stored,
  updated_at_ts timestamptz generated always as
                  (to_timestamp(updated_at / 1000.0)) stored
);

create table public.transport_legs (
  uuid          uuid primary key,
  user_id       uuid not null default auth.uid()
                  references auth.users (id) on delete cascade,
  trip_uuid     uuid not null references public.trips (uuid) on delete cascade,
  -- Constrained because the client resolves this with `TransportType.byName`,
  -- which throws on anything unexpected. Better to reject bad data at the door.
  type          text not null check (type in ('flight', 'train', 'bus')),
  departure_at  bigint not null,
  from_location text not null,
  to_location   text not null,
  updated_at    bigint not null default 0,
  deleted_at    bigint,
  departure_ts  timestamptz generated always as
                  (to_timestamp(departure_at / 1000.0)) stored,
  updated_at_ts timestamptz generated always as
                  (to_timestamp(updated_at / 1000.0)) stored
);

create table public.items (
  uuid       uuid primary key,
  user_id    uuid not null default auth.uid()
               references auth.users (id) on delete cascade,
  trip_uuid  uuid not null references public.trips (uuid) on delete cascade,
  name       text not null,
  -- Intentionally unconstrained text rather than an enum: the client's
  -- `ItemCategory.fromStorage` falls back to "other" for anything it doesn't
  -- recognise, so a new category shipped in a newer app version must not make
  -- an older server reject the whole batch.
  category   text not null default 'other',
  quantity   integer not null default 1 check (quantity >= 1),
  packed     boolean not null default false,
  updated_at bigint not null default 0,
  deleted_at bigint,
  updated_at_ts timestamptz generated always as
               (to_timestamp(updated_at / 1000.0)) stored
);

create table public.packing_lists (
  uuid       uuid primary key,
  user_id    uuid not null default auth.uid()
               references auth.users (id) on delete cascade,
  name       text not null,
  created_at bigint not null,
  updated_at bigint not null default 0,
  deleted_at bigint,
  created_at_ts timestamptz generated always as
               (to_timestamp(created_at / 1000.0)) stored,
  updated_at_ts timestamptz generated always as
               (to_timestamp(updated_at / 1000.0)) stored
);

create table public.packing_list_items (
  uuid       uuid primary key,
  user_id    uuid not null default auth.uid()
               references auth.users (id) on delete cascade,
  list_uuid  uuid not null
               references public.packing_lists (uuid) on delete cascade,
  name       text not null,
  category   text not null default 'other',
  quantity   integer not null default 1 check (quantity >= 1),
  updated_at bigint not null default 0,
  deleted_at bigint,
  updated_at_ts timestamptz generated always as
               (to_timestamp(updated_at / 1000.0)) stored
);

-- Created now so the schema is complete and RLS is uniform, but NOT synced by
-- the client yet. `storage_key` is a Supabase Storage object path — never a
-- device file path.
create table public.documents (
  uuid        uuid primary key,
  user_id     uuid not null default auth.uid()
                references auth.users (id) on delete cascade,
  trip_uuid   uuid not null references public.trips (uuid) on delete cascade,
  storage_key text,
  label       text not null,
  updated_at  bigint not null default 0,
  deleted_at  bigint,
  updated_at_ts timestamptz generated always as
                (to_timestamp(updated_at / 1000.0)) stored
);


-- ============================================================================
-- Triggers and indexes
-- ============================================================================

do $$
declare
  t text;
begin
  foreach t in array array[
    'trips', 'stays', 'transport_legs', 'items',
    'packing_lists', 'packing_list_items', 'documents'
  ]
  loop
    execute format(
      'create trigger %I_set_updated
         before insert or update on public.%I
         for each row execute function public.set_row_updated()',
      t, t
    );

    -- Exactly the pull query's access path:
    --   where user_id = auth.uid() and updated_at > cursor order by updated_at
    execute format(
      'create index %I_sync_idx on public.%I (user_id, updated_at)', t, t
    );
  end loop;
end;
$$;

-- Children are always fetched by parent, and cascades walk these.
create index stays_trip_idx on public.stays (trip_uuid);
create index transport_legs_trip_idx on public.transport_legs (trip_uuid);
create index items_trip_idx on public.items (trip_uuid);
create index documents_trip_idx on public.documents (trip_uuid);
create index packing_list_items_list_idx
  on public.packing_list_items (list_uuid);


-- ============================================================================
-- Row level security
-- ============================================================================
--
-- Every table, every operation: you may only touch your own rows. The `with
-- check` on insert and update is what stops a client forging someone else's
-- user_id.
--
-- `(select auth.uid())` rather than a bare `auth.uid()` — the subquery form is
-- evaluated once per statement instead of once per row, and lets the planner
-- use the sync index.
--
-- Note on anonymous users: they hold the `authenticated` role with an
-- `is_anonymous` claim, so these policies grant them full access to their own
-- rows. That is intended — the app is anonymous-first, and requiring a
-- permanent account here would break it. Save any `is_anonymous is false`
-- guard for the AI Edge Function later, where it limits cost abuse.

do $$
declare
  t text;
begin
  foreach t in array array[
    'trips', 'stays', 'transport_legs', 'items',
    'packing_lists', 'packing_list_items', 'documents'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);

    execute format(
      'create policy %I_select on public.%I for select to authenticated
         using ((select auth.uid()) = user_id)', t, t);
    execute format(
      'create policy %I_insert on public.%I for insert to authenticated
         with check ((select auth.uid()) = user_id)', t, t);
    execute format(
      'create policy %I_update on public.%I for update to authenticated
         using ((select auth.uid()) = user_id)
         with check ((select auth.uid()) = user_id)', t, t);
    execute format(
      'create policy %I_delete on public.%I for delete to authenticated
         using ((select auth.uid()) = user_id)', t, t);

    -- RLS decides the rows; these grants decide the verbs. Both are required.
    execute format(
      'grant select, insert, update, delete on public.%I to authenticated', t);
  end loop;
end;
$$;

-- Signed-out callers get nothing at all.
revoke all on public.trips, public.stays, public.transport_legs, public.items,
  public.packing_lists, public.packing_list_items, public.documents
  from anon;
